### ISSUE TITLE
Azure AD Equivalent

### ISSUE THREAD

**Issue by bullmoose20** [EvotecIT/ADEssentials#14]
Do you have an AADEssentials version? I like the way this works with On-premises netsed groups and memberships, but wondering if you have an equivalent for AAD (Azure AD)

**Comment by PrzemyslawKlys** [comment]
There is a plan to work on the following modules that touch Azure and Office 365 overall. Those modules are a bit outdated, but they do work. I do have plans to work on getting something similar built for Azure AD. 

List of resources:
- https://github.com/EvotecIT/PSWinDocumentation
- https://github.com/EvotecIT/PSWinDocumentation.O365
- https://github.com/EvotecIT/PSWinDocumentation.O365HealthService
- https://github.com/EvotecIT/PSWinDocumentation.AzureHealthService
- https://github.com/EvotecIT/PSWinDocumentation.Azure

Blog posts about it:
- https://evotec.xyz/pswindocumentation-export-to-word-excel-sql-of-ad-aws-exchange-o365-exchange-o365-azure-ad/
- https://evotec.xyz/getting-azure-health-parsing-html-website-using-psparsehtml/
- https://evotec.xyz/what-do-we-say-to-writing-active-directory-documentation/
- https://evotec.xyz/powershell-way-to-get-all-information-about-office-365-service-health/
- https://evotec.xyz/office-365-report-containing-user-information-and-mailbox-usage/

Unfortunately, I don't have a timeline.
