### ISSUE TITLE
Cannot Get-WinADGroupMemberOf of Identity with '@' symbol

### ISSUE THREAD

**Issue by JerHowden** [EvotecIT/ADEssentials#16]
This line in Get-WinADGroupMemberOf passes the Identity parameter to Get-WinADObject

https://github.com/EvotecIT/ADEssentials/blob/d316cc9a26ee79f10ddf82796d09b10555fc6677/Public/Get-WinADGroupMemberOf.ps1#L25

And with an @ symbol this breaks here in Get-WinADObject

https://github.com/EvotecIT/ADEssentials/blob/d316cc9a26ee79f10ddf82796d09b10555fc6677/Public/Get-WinADObject.ps1#L164

![Capture](https://user-images.githubusercontent.com/18561982/123175635-b9ce3e80-d447-11eb-973e-2496e60a70d0.PNG)

**Comment by JerHowden** [comment]
![image](https://user-images.githubusercontent.com/18561982/123175928-3a8d3a80-d448-11eb-9c7e-b09d7a63c12c.png)
 The same also happens with Get-WinADGroupMember

**Comment by PrzemyslawKlys** [comment]
I always assumed that using @ in the name means you are dealing with UPN. I was not aware people will use @ in the Name causing DN having @ sign. I was not aware it's possible to use @ in UPN as well but it seems T@ta@domain.pl is valid UPN, which complicates a lot of my scripts logic.

**Comment by JerHowden** [comment]
It is unfortunate that this naming scheme is accepted. For the Member and MemberOf scripts, would it be possible to pass along the domain name parameter in order to skip this check altogether?

**Comment by PrzemyslawKlys** [comment]
I'll just have to fix - instead of doing like *@* i will first check if it's DistiniguishedName and then if not go further. I have some ideas. Just need some time.
