### ISSUE TITLE
get-WinADGroupMember* function doesn't handle special characters in group name

### ISSUE THREAD

**Issue by torontojohnlan** [EvotecIT/ADEssentials#26]
When a group/member has "(" (bracket) in its name, the get-WinADGroupMember* functions will error out, most likely due to how group names are parsed. Bracket symbol is the only character causes problem for me, but I'd assume more special characters need escaping.

**Comment by PrzemyslawKlys** [comment]
This seems to be related to DirectorySearcher completely ignoring brackets

![image](https://user-images.githubusercontent.com/15063294/173179046-4c19472a-e4f9-42cc-ab12-df6040bb90fb.png)
![image](https://user-images.githubusercontent.com/15063294/173179056-192d9c96-5ac4-4aa7-8718-45298b0fb3db.png)

**Comment by PrzemyslawKlys** [comment]
But it seems to be more than just my code:

```powershell
Get-ADGroupMember -Identity 'GroupTest1' -Recursive | Format-Table

$adsiBob = New-Object system.directoryservices.directorysearcher "name=GroupTest1"
$adsiBob.FindOne().Properties.member | Format-Table
```

Returns only Przemyslaw Klys in both cases.
