### ISSUE TITLE
Add support for GroupManagedServiceAccount

### ISSUE THREAD

**Issue by PatrickOnGit** [EvotecIT/ADEssentials#27]
Dear

The module does not support objects of type "msDS-GroupManagedServiceAccount", which throws warnings in GPOZaurr "WARNING: Get-WinADObject - Unsupported object (S-1-5-21-xxxxxx-2233) of type msDS-GroupManagedServiceAccount. Only user,computer,group and foreignSecurityPrincipal is supported."
This type of account may be used as AGPM service account.

![image](https://user-images.githubusercontent.com/33063573/159240000-f962cacb-6c88-4ea1-93c5-64898846b1d6.png)

Please consider to enhance module to support group managed service accounts.

Thank you 
Best regards
Patrick

**Comment by PrzemyslawKlys** [comment]
The support was mostly there with -IncludeAllTypes switch. But now i added MSA and GMSA by default.
