### ISSUE TITLE
Authenticode issuer error when trying to install ADEssentials.

### ISSUE THREAD

**Issue by chongtxtx** [EvotecIT/ADEssentials#29]
I am trying to install ADEssentials, and I keep getting hung up with either the PSEventViewer module or the PSWriteHTML module. It keeps saying that the module is not atching with the authenticode issuer. I've installed the modules individually, but the install script still fails out when it gets to that installation piece. I've uninstalled the modules and let the ADEssentials install script try to do its thing but to no avail. Please let me know if there are any workarounds for this. Here is a quick snippet of the error I see. 

`VERBOSE: Hash for package 'ADEssentials' does not match hash provided from the server.
VERBOSE: InstallPackageLocal' - name='ADEssentials', version='0.0.145',destination='C:\Users\rodolfo.ybarra\AppData\Local\Temp\689443725'
VERBOSE: Catalog file 'PSEventViewer.cat' is not found in the contents of the module 'PSEventViewer' being installed.
VERBOSE: Valid authenticode signature found in the file 'PSEventViewer.psd1' for the module 'PSEventViewer'.
VERBOSE: For publisher validation, current module 'PSEventViewer' with version '1.0.22' with publisher name 'System.Object[]'. Is this module signed by Microsoft: 'False'.
VERBOSE: For publisher validation, using the previously-installed module 'PSEventViewer' with version '1.0.22' under 'C:\Program Files\WindowsPowerShell\Modules\PSEventViewer\1.0.22' with publisher name 'System.Objec
t[]'. Is this module signed by Microsoft: 'False'.
PackageManagement\Install-Package : Authenticode issuer 'System.Object[]' of the new module 'PSEventViewer' with version '1.0.22' is not matching with the authenticode issuer 'System.Object[]' of the 
previously-installed module 'PSEventViewer' with version '1.0.22'. If you still want to install or update, use -SkipPublisherCheck parameter.
At C:\Program Files (x86)\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : AuthenticodeIssuerMismatch,Validate-ModuleAuthenticodeSignature,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
 

PS C:\Windows\system32> `

**Comment by PrzemyslawKlys** [comment]
```powershell
Install-Module ADessentials -Force -Verbose -SkipPublisherCheck 
```

I guess it may be due to a change from SHA1 to SHA256 on my end.
