### ISSUE TITLE
Functions not loading completely

### ISSUE THREAD

**Issue by everydaylearner** [EvotecIT/ADEssentials#34]
Hi, 
Some reason not all functions are loading completely. I dont see good amount of functions. when i do import-module ADEssentials, it loads ok, no errors etc. but when i do Get-Command -Module ADEssentials  I only see limit number of functions loaded.  AM i missing something? 

PS C:\Program Files\WindowsPowerShell\Modules\ADEssentials\0.0.148> Get-Command -Module ADESsentials

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Alias           Get-WinADTrusts                                    0.0        ADEssentials
Alias           Get-WinDNSServerIP                                 0.0        ADEssentials
Alias           Show-ADGroupMember                                 0.0        ADEssentials
Alias           Show-ADGroupMemberOf                               0.0        ADEssentials
Alias           Show-ADTrust                                       0.0        ADEssentials
Alias           Show-ADTrusts                                      0.0        ADEssentials
Alias           Show-WinADTrusts                                   0.0        ADEssentials
Function        Get-DNSServerIP                                    0.0        ADEssentials
Function        Get-WinADDomain                                    0.0        ADEssentials
Function        Get-WinADForest                                    0.0        ADEssentials
Function        Get-WinADGroupMember                               0.0        ADEssentials
Function        Get-WinADGroupMemberOf                             0.0        ADEssentials
Function        Get-WinADObject                                    0.0        ADEssentials
Function        Get-WinADTrust                                     0.0        ADEssentials
Function        Get-WinDNSIPAddresses                              0.0        ADEssentials
Function        New-ADSite                                         0.0        ADEssentials
Function        Set-WinADForestACLOwner                            0.0        ADEssentials
Function        Show-WinADDNSRecords                               0.0        ADEssentials
Function        Show-WinADGroupMember                              0.0        ADEssentials
Function        Show-WinADGroupMemberOf                            0.0        ADEssentials
Function        Show-WinADTrust                                    0.0        ADEssentials
Function        Test-WinADVulnerableSchemaClass                    0.0        ADEssentials

thank you!

**Comment by PrzemyslawKlys** [comment]
To prevent issues on the module and let it run some functions that don't require any dependencies we have a custom logic implemented for when the commands are exported. If you want to have all commands exported you need to make sure you have RSAT AD, RSAT DNS and RSAT GPO all 3 installed, and working.

**Comment by everydaylearner** [comment]
thank you so much! That did the trick. Installing RSAT AD. it is working as expected now!
