### ISSUE TITLE
PSWriteHTML files missing or mislabeled

### ISSUE THREAD

**Issue by workderrek** [EvotecIT/ADEssentials#37]
```
PS C:\Windows\system32> Show-ADGroupMember -Identity support -online
WARNING: Add-HTMLStyle - File C:\Program Files\WindowsPowerShell\Modules\PSWriteHTML\1.0.0\..\Resources\CSS\datatables.noscript.css not found.
 Unable to load CSS to HTML. HTML may be broken. Skipping.
WARNING: Add-HTMLScript - File C:\Program Files\WindowsPowerShell\Modules\PSWriteHTML\1.0.0\..\Resources\JS\dataTables.conditions.js not found
. Unable to load JavaScript to HTML. HTML may be broken. Skipping.
WARNING: Add-HTMLScript - File C:\Program Files\WindowsPowerShell\Modules\PSWriteHTML\1.0.0\..\Resources\JS\escapeRegex.js not found. Unable t
o load JavaScript to HTML. HTML may be broken. Skipping.
WARNING: Add-HTMLScript - File C:\Program Files\WindowsPowerShell\Modules\PSWriteHTML\1.0.0\..\Resources\JS\tabbis.js not found. Unable to loa
d JavaScript to HTML. HTML may be broken. Skipping.
WARNING: Add-HTMLScript - File C:\Program Files\WindowsPowerShell\Modules\PSWriteHTML\1.0.0\..\Resources\JS\tabbisAdditional.js not found. Una
ble to load JavaScript to HTML. HTML may be broken. Skipping.

```
Looks like the issue is here: C:\Program Files\WindowsPowerShell\Modules\PSWriteHTML\1.0.0\\..\

The files that can't be found in the first error are here: C:\Program Files\WindowsPowerShell\Modules\PSWriteHTML\1.0.0\Resources\CSS

![Screenshot_1](https://github.com/EvotecIT/ADEssentials/assets/79885324/da1f9270-7290-45c0-b8a8-7ab03bd25e5e)

There are far more errors if you don't use the -online flag.

**Comment by workderrek** [comment]
Used a little help from ChatGPT to make symbolic links between the place the script is looking and where the files actually are. Seems to be working:

`# Array of file names
$filenames = @(
    "fontsAwesome.min.css",
    "jquery.min.js",
    "moment.min.js",
    "dataTables.jquery.min.css",
    "dataTables.select.min.css",
    "dataTables.jquery.min.js",
    "dataTables.select.min.js",
    "dataTables.datetimeMoment.js",
    "datatables.buttons.min.css",
    "dataTables.buttons.min.js",
    "jszip.min.js",
    "datatables.buttons.html5.min.js",
    "pdfmake.min.js",
    "vfs_fonts.min.js",
    "dataTables.dateTime.css",
    "dataTables.dateTime.js",
    "dataTables.responsive.min.css",
    "dataTables.responsive.min.js",
    "dataTables.searchBuilder.css",
    "dataTables.searchBuilder.js",
    "vis-data.min.js",
    "vis-network.min.css",
    "vis-network.min.js",
    "vis-networkLoadDiagram.js",
    "vis-network.loadingbar.css",
    "datatables.noscript.css",
    "dataTables.conditions.js",
    "escapeRegex.js",
    "tabbis.js",
    "tabbisAdditional.js",
    "redrawObjects.js",
    "datatables.noscript.css",
    "dataTables.conditions.js",
    "escapeRegex.js",
    "tabbis.js",
    "tabbisAdditional.js"
)

$sourcePath = "C:\Program Files\WindowsPowerShell\Modules\PSWriteHTML\1.0.0\Resources"
$destPath = "C:\Program Files\WindowsPowerShell\Modules\PSWriteHTML\Resources"

# If destination folders don't exist, create them
if (!(Test-Path "$destPath\CSS")) {
    New-Item -ItemType Directory -Path "$destPath\CSS" -Force
}

if (!(Test-Path "$destPath\JS")) {
    New-Item -ItemType Directory -Path "$destPath\JS" -Force
}

foreach ($filename in $filenames) {
    if ($filename -like "*.js") {
        $srcFile = Join-Path -Path $sourcePath -ChildPath "JS\$filename"
        $destFile = Join-Path -Path $destPath -ChildPath "JS\$filename"
    } else {
        $srcFile = Join-Path -Path $sourcePath -ChildPath "CSS\$filename"
        $destFile = Join-Path -Path $destPath -ChildPath "CSS\$filename"
    }

    if (Test-Path $srcFile) {
        New-Item -ItemType SymbolicLink -Path $destFile -Target $srcFile -Force
        Write-Host "Created link for $filename"
    } else {
        Write-Host "Source file $srcFile not found. Skipping."
    }
}
`

**Comment by PrzemyslawKlys** [comment]
Remove the new PSWriteHTML and redownload the newest version. It seems there's a bug in 1.0.0.

**Comment by PrzemyslawKlys** [comment]
Install-Module PSWriteHTML -Force -Verbose should fix your problem.
