### ISSUE TITLE
PublisherCheck Error

### ISSUE THREAD

**Issue by Heinzler** [EvotecIT/ADEssentials#38]
PackageManagement\Install-Package : Authenticode issuer 'CN=Przemysław Kłys EVOTEC, O=Przemysław Kłys
EVOTEC, L=Mikołów, C=PL' of the new module 'PSWriteHTML' with version '1.9.0' from root certificate
authority 'CN=DigiCert Trusted Root G4, OU=www.digicert.com, O=DigiCert Inc, C=US' is not matching with
the authenticode issuer 'CN=Przemysław Kłys EVOTEC, O=Przemysław Kłys EVOTEC, L=Katowice, S=Śląskie, C=PL'
of the previously-installed module 'PSWriteHTML' with version '0.0.190' from root certificate authority
'CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US'.

**Comment by PrzemyslawKlys** [comment]
I've changed certificate for my modules few months ago. This means you need to do -SkipPublisherCheck when installing modules that are already installed and have diff certificate.
