### ISSUE TITLE
Merge existing Reports

### ISSUE THREAD

**Issue by CryoRig** [EvotecIT/ADEssentials#42]
Hi
thanks for the amazing module!

I just spent some time generating reports and was wondering if there is a way to merge some of them together?
Basically i missed a group and created reports for Groupo A and B but later noticed that they both are Members of Group C.
Would it be possible to merge the existing Reports of A and B instead of running the command again for Group C?

**Comment by PrzemyslawKlys** [comment]
not really, no. you could do it manually, but you need to figure out HTML schema yourself.
