### ISSUE TITLE
Latest release full change log v0.0.192 to v0.0.192

### ISSUE THREAD

**Issue by red-erik** [EvotecIT/ADEssentials#43]
Hello,
we don't see any modifications at all.

![image](https://github.com/EvotecIT/ADEssentials/assets/10245160/cde7bb11-2cb2-4825-8197-3ee4a5edef66)

Regards,
Red.

**Comment by PrzemyslawKlys** [comment]
How is that supposed to work? Comparing 192 to 192 - means 0 changes?

- https://github.com/EvotecIT/ADEssentials/compare/v0.0.191...v0.0.192
