### ISSUE TITLE
Null reference object in Test-DNSNameServers

### ISSUE THREAD

**Issue by PHactotum** [EvotecIT/ADEssentials#44]
When running Test-DNSNameServers receive the comment, "Failed to get the zone information for contoso.com on server DC1.contoso.com...."

This appears to be a result of the Jan 2024 commit [Convert scriptblock filter to string filter](https://github.com/EvotecIT/ADEssentials/commit/1e3d5453bc18f1f63cbbe1071d075bc314a7ee70) 

```
PS > Get-ADDomainController -Server $domain -Filter "IsReadOnly -eq '$False'"|measure


Count    : 0
Average  :
Sum      :
Maximum  :
Minimum  :
Property :



PS > Get-ADDomainController -Server $domain -Filter {IsReadOnly -eq $false}|measure


Count    : 17
Average  :
Sum      :
Maximum  :
Minimum  :
Property :
```

I'm not sure how to write this as a string filter that will work.  I know the AD cmdlets often cause me to revert to scriptblock filters.

Tested on Windows 10 22H2, with PowerShell 5.1.19041.4291

**Comment by PrzemyslawKlys** [comment]
It's actually `Get-ADDomainController -Server $domain -Filter 'IsReadOnly -eq $false' |ft` that works so need to fix it. Thank you for reporting. Maybe you could PR it
