### ISSUE TITLE
Not able to run Invoke-ADEssentials

### ISSUE THREAD

**Issue by adamgell** [EvotecIT/ADEssentials#45]
https://github.com/EvotecIT/ADEssentials/blob/master/Public/Invoke-ADEssentials.ps1

Trying to run this script. I don't see the function being exported in the module. Tried a number of different versions, computers, and PowerShell versions.

Can you help point me in the right direction? 

![image](https://github.com/EvotecIT/ADEssentials/assets/27519/d2b5d10c-78a8-45d7-96ff-7a5b017a894c)
![image](https://github.com/EvotecIT/ADEssentials/assets/27519/1bea632b-32ed-413a-b8e0-e46570f65cb5)

**Comment by PrzemyslawKlys** [comment]
You need to install rsat for ad and gpo. Without it it will hide a lot of functions.

**Comment by adamgell** [comment]
ahh thanks! that makes sense!
