### ISSUE TITLE
added help for this module

### ISSUE THREAD

**Issue by neztach** [EvotecIT/ADEssentials#46]
same as O365Essentials - I forked ADEssentials and added help.

woo! I hope it helps

**Comment by PrzemyslawKlys** [comment]
What about PR? :)

**Comment by neztach** [comment]
sorry I guess I need to learn more about GitHub.  Not sure how to do a Pull Request yet.

Are my help additions unable to be used until I get down Pull Requests?

**Comment by PrzemyslawKlys** [comment]
Well you did PR's, several of them now. So we're good. I need to now review them - hopefully during weekend. Thank you!

**Comment by neztach** [comment]
honestly, I'm hoping that not only to help you get the documentation you want, I might be able to entice you to resurrect testimo (joking ,,,,kind of).

**Comment by PrzemyslawKlys** [comment]
Testimo is not forgotten or deprecated. I'm working on tools around Testimo that will hopefully allow Testimo Pro or similar to exists. There's a reason I've created OfficeIMO, HtmlForgeX, Mailozaurr being rewritten in c#, PSEventViewer being rewritten in c# and so on. The end goal is that most likely Testimo will sort of get a rewrite as well to be much faster.

**Comment by PrzemyslawKlys** [comment]
Thank you, commited ;)
