### ISSUE TITLE
no commands exist in some functions

### ISSUE THREAD

**Issue by ironbe4rd** [EvotecIT/ADEssentials#7]
you dont even have a command in these functions to get the data.
get-winadproxyaddresses
Get-WinADUserPrincipalName

perhaps others as well im not going to go through all of them

**Comment by PrzemyslawKlys** [comment]
Can you be more specific - where exactly are you looking? 

Published version when I search for: `Get-WinADProxyAddresses`
- https://www.powershellgallery.com/packages/ADEssentials/0.0.65/Content/ADEssentials.psm1

GitHub version:

https://github.com/EvotecIT/ADEssentials/blob/cb2f48d20c6a8623589b22f882d508b7a8510395/Public/Get-WinADProxyAddresses.ps1#L1-L71

So where do you miss things or what is not working for you?

**Comment by PrzemyslawKlys** [comment]
Unless you're looking for a use case:

```powershell
$ADUsers = Get-ADUser -Filter * -Properties ProxyAddresses
foreach ($User in $ADUsers) {
    Get-WinADProxyAddresses -ADUser $User
}
```

```powershell
$ADUsers = Get-ADUser -Filter * -Properties ProxyAddresses
foreach ($User in $ADUsers) {
    Get-WinADProxyAddresses -ADUser $User -RemovePrefix
}
```

**Comment by PrzemyslawKlys** [comment]
Not all commands are publicly usable, I use them in other cases, that may not be obvious at first sight.

**Comment by ironbe4rd** [comment]
Ah i see now what you mean. That is how i ended up using it anyway. Usually with these functions I would expect the actual commands to get the property to be in the Function, here you are just formatting the data.

**Comment by PrzemyslawKlys** [comment]
Well, I don't know what use case there may be for you. In this case, I'm requesting all users, but in others, I may request just couple of users that require fixing. When there are too many variables in place I usually just create helper function rather than do it all for me. In other cases, there's a full "fix it for me please".

**Comment by ironbe4rd** [comment]
While I have you. How do you use repair-winademailaddress?

I keep getting cannot find object on the username.

**Comment by PrzemyslawKlys** [comment]
Lemme fix this one. I see an edge case I've not thought of on this one.

**Comment by PrzemyslawKlys** [comment]
This would be your use case

```powershell
# Get a user
$User = Get-ADUser 'testing1' -Properties ProxyAddresses, EmailAddress
# You can optionally verify how it looks like or what is set
#Get-WinADProxyAddresses -ADUser $User | Format-Table
# Fix primary email address - it will be added to primary email field + proxy address as primary, existing addresses will be rearanged
Repair-WinADEmailAddress -ADUser $User -ToEmail 'testing2@evotec.xyz' -Display -WhatIf | Format-Table
```

-WhatIf shows what will happen
-Display will give you an output like this:

![image](https://user-images.githubusercontent.com/15063294/90290602-747fce80-de7e-11ea-9d67-f63c20aa9e4f.png)

For example:

```powershell
# Get a user
$User = Get-ADUser 'testing1' -Properties ProxyAddresses, EmailAddress
# You can optionally verify how it looks like or what is set
#Get-WinADProxyAddresses -ADUser $User | Format-Table
# Fix primary email address - it will be added to primary email field + proxy address as primary, existing addresses will be rearanged
Repair-WinADEmailAddress -ADUser $User -ToEmail 'testing2@evotec.be' -Display -WhatIf | Format-Table
```

![image](https://user-images.githubusercontent.com/15063294/90290637-85304480-de7e-11ea-8ac9-09ff02729ed5.png)

Without WHATIF

![image](https://user-images.githubusercontent.com/15063294/90290672-97aa7e00-de7e-11ea-9534-d44b8b7b410f.png)

**Comment by PrzemyslawKlys** [comment]
Update-Module ADEssentials. I've released one with fixes.

**Comment by ironbe4rd** [comment]
Thanks updates are greatly appreciated!
