### ISSUE TITLE
Feature Request - Show-ADGroupMember "silent" parameter 

### ISSUE THREAD

**Issue by Zerrtified** [EvotecIT/ADEssentials#8]
A parameter for Show-ADGroupMember that would allow the user to generate the HTML report without invoking it would be very useful for automating regular report generation. I'm keen to schedule regular reports of my top level group memberships and invoking 1275 reports as they're being generated isn't ideal.

**Comment by PrzemyslawKlys** [comment]
Will be added.

**Comment by PrzemyslawKlys** [comment]
It seems it's getting PR https://github.com/EvotecIT/ADEssentials/pull/9
